### ISSUE TITLE
Reading .3ds files

### ISSUE THREAD

**Issue by mwisniewski0** [mwisniewski0/Real-Time-Photon-Mapper#2]
We need a functionality that:

- Takes as an input a path to a 3ds file
- Returns a list of triangles in the scene:
    - Each triangle needs to have its vertices stored in CCW order. This will be used to encode the information about the direction of the normal of the triangle.
    - Each triangle needs to link to the material it is made of
    - Each triangle can contain any extra information needed to connect it to the material (e.g. texels in the texture, etc.)
- Returns a list of light sources
- Returns a list of materials

This issue should be expanded as more is learned about the format of the 3ds files.

**Comment by bcarlborg** [comment]
I am also not sure if the 3ds library is parsing the vertices for objects with coordinates relative to an objects center, or to a global center. So I am not sure if some transformation needs to be done to the vertices before adding them to the output.

**Comment by mwisniewski0** [comment]
Closing this, since we moved to .obj
