### ISSUE TITLE
Use CMake to manage the project

### ISSUE THREAD

**Issue by mwisniewski0** [mwisniewski0/Real-Time-Photon-Mapper#25]
All of our development machines use different OSes (we have Windows, OSX and Linux). Using CMake would make it much easier to work across the platforms, and it would make deploying on different OSes easier as well. This could also allow for some sort of dependency management system such as Hunter, cget or Conan.

More research is needed.

**Comment by mwisniewski0** [comment]
@bcarlborg, please report your findings on this topic so far

**Comment by bcarlborg** [comment]
CMake is certainly the right tool for this project. Currently I have been using a small set of CMake files to manage my project, and in the future we will continue with this build system
