### ISSUE TITLE
Change stage1 to use common code

### ISSUE THREAD

**Issue by samkottler** [mwisniewski0/Real-Time-Photon-Mapper#35]
Modify stage 1 (photon tracing) to use common geometry etc code.

**Comment by samkottler** [comment]
@mwisniewski0, can you move the initScene function from the Renderer class to something shared. We can use the same scene reading function for both stages.

**Comment by mwisniewski0** [comment]
@samkottler please reference the appropriate commit here and close this issue since this has been finished

**Comment by samkottler** [comment]
Finished in: 7cfe71c
