### ISSUE TITLE
Refractive surfaces in stage 2

### ISSUE THREAD

**Issue by mwisniewski0** [mwisniewski0/Real-Time-Photon-Mapper#5]
For increased realism in the rendered scene, we need to add refractive surfaces. Part of this needs to be processed within the real-time renderer since refractive surfaces will look differently dependent on the angle from which we are looking at them.

**Comment by mwisniewski0** [comment]
@samkottler Please verify that the refractions look realistic.

**Comment by samkottler** [comment]
Not quite realistic. Rays will sometimes reflect even with perfectly refractive surfaces. Take a look at Schlick's approximation. This should take care of internal reflection also.

**Comment by mwisniewski0** [comment]
Thanks for the input. I'll look into that after I get BVHs figured out.
