### ISSUE TITLE
Preliminary visualization of photons created in stage 1

### ISSUE THREAD

**Issue by mwisniewski0** [mwisniewski0/Real-Time-Photon-Mapper#8]
In order for quick debugging of the photon mapping pre-rendering in stage 1, we will include tools for visualizing the photon map by showing photons as dots in stage 2. This way, we can see that shaded areas have less photons, and caustics have extra photons.

**Comment by samkottler** [comment]
I made something very simple for this, but it has a weird thing where which direction a surface is facing affects the density of photons and therefore looks brighter. It might be nice for this to visualization to take into account the normals.

**Comment by samkottler** [comment]
Finished by 37ef2dc
